#ifndef Definitions_h
#define Definitions_h
#include "Arduino.h"

  #define DEBUG_CONTROLLER false
  #define INITIAL_TEST_DELAY 3000

//PIN DEFINITIONS
  //LED/BUTTON 1
  #define RCS_LED_PIN 15
  #define RCS_BUTTON_PIN 46
  //LED/BUTTON 2
  #define SAS_LED_PIN 18
  #define SAS_BUTTON_PIN 53
  //ON/OFF SWITCHES
  #define CHUTES_BUTTON_PIN 51
  #define LADDER_BUTTON_PIN 49
  #define LIGHT_BUTTON_PIN 50
  #define SOLAR_BUTTON_PIN 48
  #define LANDINGGEAR_BUTTON_PIN 47
  #define BRAKES_BUTTON_PIN 52
  //LED
  #define EVA_LED_PIN 17 //ESCAPE VELOCITY ACHIEVED
  #define DFX_LED_PIN 16 //DANGE G FORCE TOO EXTREME
  #define SFL_LED_PIN 3 //SOLID FUEL LOW
  #define LFL_LED_PIN 2 //LIQUID FUEL LOW
  #define EFL_LED_PIN 14 //ELETRIC FUEL LOW
  //LCDS
  #define LCD_TOP_PIN 11
  #define LCD_MID_PIN 10
  #define LCD_BOT_PIN 12
  //THROTTLE
  #define THROTTLE_PIN A9
  //LIGHT BUTTONS
  #define STAGE_BUTTON_PIN 33
  #define IGNITE_BUTTON_PIN 37
  //JOYSTICK 1 - ROTATION
  #define JOYSTICK1_LEFT_PIN A5
  #define JOYSTICK1_RIGHT_PIN A6
  #define JOYSTICK1_TOP_PIN A1
  #define JOYSTICK1_BOTTOM_PIN A4
  //JOYSTICK 2 - TRANSATION
  #define JOYSTICK2_LEFT_PIN A7
  #define JOYSTICK2_RIGHT_PIN A2
  #define JOYSTICK2_TOP_PIN A3
  #define JOYSTICK2_BOTTOM_PIN A8
//Components stuff
  #define THROTTLE_MIN_VALUE 0
  #define THROTTLE_MAX_VALUE 1000
  //
  #define JOYSTICK_MIN 0
  #define JOYSTICK_MAX 1000
  //
  #define LCD_REFRESH_DELAY 250

#endif
